### ISSUE TITLE
TC Crash issue

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#3267]
### Description
* All test cases are passed but the crash occurs.
* It is a pretty rare case. (Maybe twice a month)

### Jira
* https://code.sec.samsung.net/jira/browse/TSDF-1644
* https://code.sec.samsung.net/jira/browse/TSDF-1704

### Test case
* utc_nnstreamer_capi_element_set_string_property_p

### Log
```
05-08 20:36:28.509+0900 I/NativeTCT (P22523, T22523): [app_control:64] Executing TC Name = utc_nnstreamer_capi_element_set_string_property_p
05-08 20:36:28.509+0900 I/NativeTCT (P22523, T22523): utc_nnstreamer_capi_element_set_string_property_p : Startup begin
05-08 20:36:28.509+0900 I/NativeTCT (P22523, T22523): utc_nnstreamer_capi_element_set_string_property_p : Startup end
05-08 20:36:28.509+0900 I/NativeTCT (P22523, T22523): utc_nnstreamer_capi_element_set_string_property_p : Body begin
05-08 20:36:28.509+0900 D/nnstreamer (P22523, T22523): Converted pipeline: videotestsrc ! video/x-raw,format=RGB,width=640,height=480 ! videorate max-rate=1 ! tensor_converter ! tensor_mux ! tensor_demux name=demux ! tensor_sink
05-08 20:36:28.512+0900 D/nnstreamer (P22523, T22523): The pipeline state changed from NULL to READY.
05-08 20:36:28.602+0900 I/CRASH_MANAGER (P25954, T25954): crash-manager.c: run(1287) > Creating report for pid 22523, tid 25637, cmdline /opt/usr/globalapps/org.tizen.nnstreamer-native-utc/bin/nnstreamer-native-utc, pkgid org.tizen.nnstreamer-native-utc
05-08 20:36:28.602+0900 I/CRASH_MANAGER (P25954, T25954): crash-manager.c: execute_crash_modules(950) > Starting the minicoredumper
```

### Call Stack
```bash
#0  0xb69287a4 in gst_tensor_demux_get_tensor_pad (total=<optimized out>, 
    nth=17006632, created=<synthetic pointer>, tensor_demux=0xac407f70)
    at /usr/src/debug/nnstreamer-1.7.1-83.1.arm/gst/nnstreamer/tensor_demux/gsttensordemux.c:370
#1  gst_tensor_demux_chain (pad=<optimized out>, parent=<optimized out>, 
    buf=0xacdbfa58 [None])
    at /usr/src/debug/nnstreamer-1.7.1-83.1.arm/gst/nnstreamer/tensor_demux/gsttensordemux.c:485
#2  0xb6877134 in ?? () from /lib/libgstreamer-1.0.so.0
#3  0xb6878b18 in ?? () from /lib/libgstreamer-1.0.so.0
#4  0xb687e522 in gst_pad_push () from /lib/libgstreamer-1.0.so.0
#5  0xb692a6bc in gst_tensor_mux_send_segment_event (
    dts=-1 [-1:59:59.999999999], pts=0 [0:00:00.000000000], 
    tensor_mux=0x1036040)
    at /usr/src/debug/nnstreamer-1.7.1-83.1.arm/gst/nnstreamer/tensor_mux/gsttensormux.c:434
#6  gst_tensor_mux_collected (pads=<optimized out>, tensor_mux=0x1036040)
    at /usr/src/debug/nnstreamer-1.7.1-83.1.arm/gst/nnstreamer/tensor_mux/gsttensormux.c:489
```

### Possible solution
* Add locking mechanism in `tensor_demux`
* Update test case.

**Comment by myungjoo** [comment]
> Add locking mechanism in tensor_demux

Have you already found the cause?

**Comment by again4you** [comment]
This issue is fixed.
