### ISSUE TITLE
Additional instructions for tensor_filter with python3 framework

### ISSUE THREAD

**Issue by mholtta** [nnstreamer/nnstreamer#3757]
# Additional instructions for tensor_filter with python3 framework
Would it be possible to get additional information on what is needed to run tensor_filter with framework=python3? And also information on what is needed to setup Python environment such that importing nnstreamer_python in python would work?

My current issue seems to be that GStreamer doesn't find the nnstreamer-python elements and tensor_filter doesn't recognize `framework=python3`. Additionally, nnstreamer_python cannot be imported in Python. Pipelines with tensor_filter with TensorFlow Lite framework work as expected.

How to Reproduce
===============
1. Build dockerimage (image definition below)
2. Rename [passthrough.py](https://github.com/nnstreamer/nnstreamer/blob/2a42dda5b773d4c1a7ba29db7faa611f6eb0c6fe/tests/test_models/models/passthrough.py) to nnnstreamer_filter_passthrough.py, run the dockerimage while mounting nnnstreamer_filter_passthrough.py
3. Run test pipeline (below)
4. See error (below)

**I tested the below pipeline with tensor_filter python3 framework:**
`gst-launch-1.0 videotestsrc num-buffers=1 ! video/x-raw,format=RGB,width=280,height=40,framerate=0/1 ! videoconvert ! video/x-raw, format=RGB ! tensor_converter ! tee name=t ! queue ! tensor_filter framework=python3 model=nnnstreamer_filter_passthrough.py input=\"3:280:40:1\" inputtype=\"uint8\" output=\"3:280:40:1\" outputtype=\"uint8\" ! filesink location=\"testcase1.passthrough.log\" sync=true t. ! queue ! filesink location=\"testcase1.direct.log\" sync=true`

The pipeline has been adopted from nnstreamer unittests - [see this link](https://github.com/nnstreamer/nnstreamer/blob/2a42dda5b773d4c1a7ba29db7faa611f6eb0c6fe/tests/nnstreamer_filter_python3/runTest.sh#L68). The nnstreamer_filter_passthrough.py in the pipeline is passthrough.py from nnstreamer unittests - [see link here](https://github.com/nnstreamer/nnstreamer/blob/2a42dda5b773d4c1a7ba29db7faa611f6eb0c6fe/tests/test_models/models/passthrough.py).

**The resulting error from running the pipeline:**
```
(gst-plugin-scanner:1392): GStreamer-WARNING **: 13:37:06.789: Failed to load plugin '/usr/lib/nnstreamer/decoders/libnnstreamer_decoder_python3.so': nnstreamer_python3.so: cannot open shared object file: No such file or directory
(gst-plugin-scanner:1392): GStreamer-WARNING **: 13:37:06.802: Failed to load plugin '/usr/lib/nnstreamer/filters/libnnstreamer_filter_python3.so': nnstreamer_python3.so: cannot open shared object file: No such file or directory
(gst-plugin-scanner:1392): GStreamer-WARNING **: 13:37:06.804: Failed to load plugin '/usr/lib/nnstreamer/converters/libnnstreamer_converter_python3.so': nnstreamer_python3.so: cannot open shared object file: No such file or directory
** (gst-plugin-scanner:1392): CRITICAL **: 13:37:06.808: Cannot open python3(/usr/lib/nnstreamer/converters/libnnstreamer_converter_python3.so) with error nnstreamer_python3.so: cannot open shared object file: No such file or directory.
** (gst-launch-1.0:1391): CRITICAL **: 13:37:07.207: Cannot open python3(/usr/lib/nnstreamer/converters/libnnstreamer_converter_python3.so) with error nnstreamer_python3.so: cannot open shared object file: No such file or directory.
** (gst-launch-1.0:1391): CRITICAL **: 13:37:07.208: Cannot open python3(/usr/lib/nnstreamer/filters/libnnstreamer_filter_python3.so) with error nnstreamer_python3.so: cannot open shared object file: No such file or directory.
** (gst-launch-1.0:1391): WARNING **: 13:37:07.208: Cannot identify the given neural network framework, python3
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps2)' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_pad_template_new: assertion 'caps != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_element_request_compatible_pad: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_object_unref: assertion 'object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.212: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps2)' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_pad_template_new: assertion 'caps != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_element_request_compatible_pad: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_object_unref: assertion 'object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:1391): GStreamer-CRITICAL **: 13:37:07.213: gst_mini_object_ref: assertion 'mini_object != NULL' failed
WARNING: erroneous pipeline: could not link queue0 to tensorfilter0
```

**Testing Python import in bash (same container):**
```
 python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nnstreamer_python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nnstreamer_python'
```

Further Information
===============
The tests were performed in a container with the following container definition (Ubuntu based container):
```
FROM osrf/ros:galactic-desktop

RUN sudo apt-get update \
    && sudo apt-get upgrade -y \
    && sudo apt-get install -y --no-install-recommends \
    python3-pip \
    ros-galactic-ros2bag \
    ros-galactic-rosbag2-storage-default-plugins \
    ffmpeg \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio python3-gi libgirepository1.0-dev libcairo2-dev gir1.2-gstreamer-1.0 \
    && pip install pipenv \
    && echo "source /opt/ros/galactic/setup.bash" >> ~/.bashrc \
    && rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update \
    && sudo apt-get install -y --no-install-recommends  software-properties-common \
    && sudo apt-add-repository ppa:nnstreamer \
    && sudo apt-get install -y \
        nnstreamer \
        nnstreamer-tensorflow-lite \
        nnstreamer-python3

ENV GST_PLUGIN_PATH=/usr/lib/nnstreamer
ENV PYTHONPATH=/usr/lib/nnstreamer
```
I tried adding `/usr/lib/nnstreamer` to both `GST_PLUGIN_PATH` and `PYTHONPATH`, but that made no difference.

In addition, command `pipenv install --dev` is run right after running the container. However, pipenv doesn't contain any nnstreamer_python related dependencies. Only possibly relevant Python module for this example in pipenv is numpy.

**Comment by gichan-jang** [comment]
@mholtta Thanks for postring the issue.
I reproduced the same problem. I will find the solution and upload the patch.

**Comment by gichan-jang** [comment]
We have confirmed that there are some problems with the library(nnstreamer_python3.so) link.
We will find a proper way soon.
As a temporary solution, please set the LD_LIBRARY_PATH.
```
$ export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:/usr/lib/nnstreamer/extra
```

**Comment by mholtta** [comment]
Thank you for the very quick response!
I tested the suggestion to set the `LD_LIBRARY_PATH`. The error changed a bit to missing nnstreamer_python module in Python. Indeed I cannot import nnstreamer_python in Python. 

Could you provide advice on what is needed to setup the Python environment? Thank you!

See the current error below:
```
 gst-launch-1.0 videotestsrc num-buffers=1 ! video/x-raw,format=RGB,width=280,height=40,framerate=0/1 ! videoconvert ! video/x-raw, format=RGB ! tensor_converter ! tee name=t ! queue ! tensor_filter framework=python3 model=nnnstreamer_filter_passthrough.py input=\"3:280:40:1\" inputtype=\"uint8\" output=\"3:280:40:1\" outputtype=\"uint8\" ! filesink location=\"testcase1.passthrough.log\" sync=true t. ! queue ! filesink location=\"testcase1.direct.log\" sync=true
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.311: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.311: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.312: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.312: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.312: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.313: Cannt find `nnstreamer_python` module
failed to initailize the object: Python

** (gst-launch-1.0:12131): WARNING **: 12:05:37.313: Given input info is invalid, cannot get output info.
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.313: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.314: Cannt find `nnstreamer_python` module
failed to initailize the object: Python

** (gst-launch-1.0:12131): WARNING **: 12:05:37.314: Given input info is invalid, cannot get output info.
Setting pipeline to PAUSED ...
ModuleNotFoundError: No module named 'nnstreamer_python'

** (gst-launch-1.0:12131): CRITICAL **: 12:05:37.316: Cannt find `nnstreamer_python` module
failed to initailize the object: Python
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by gichan-jang** [comment]
I think you installed `nnstreamer-python3` using apt. (`sudo apt install nnstreamer-python3`)
Then, the library file is located at `/usr/lib/python3/dist-packages/nnstreamer_python.so`
And please check this command works,
`python3 -c "import nnstreamer_python"`

If you failed to load nnstreamer python module, you will get this error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nnstreamer_python'
```
If there is no message, the module is successfully loaded.
Please check above things.

**Comment by mholtta** [comment]
Thank you for the assistance, now nnstreamer-python is working as expected. The issue was on my side - I was working in a virtual environment (with pipenv) and that environment couldn't see the apt intalled modules. Following [these](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#working-with-platform-provided-python-components) pointers helped.

**Comment by gichan-jang** [comment]
Close this issue via #3762
