### ISSUE TITLE
 gst_parse_error: could not link tensortransform0 to tensorfilter0 (3)

### ISSUE THREAD

**Issue by TUT-jiayou** [nnstreamer/nnstreamer#3950]
Having problems with a source code of a github repository?

Having problems with the CI bot that controls the build process?

Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

# Issue Description
* Install demo from ubuntu:ppa
···
$ sudo add-apt-repository ppa:nnstreamer/ppa
$ sudo apt-get update
$ sudo apt-get install nnstreamer
$ sudo add-apt-repository ppa:nnstreamer-example/ppa
$ sudo apt-get update
$ sudo apt-get install nnstreamer-example
$ cd /usr/lib/nnstreamer/bin
···
* installed packages `sudo apt list --installed | grep nnstreamer`
```
nnstreamer/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装]
nnstreamer-configuration/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装，自动]
nnstreamer-core/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装，自动]
nnstreamer-edge/bionic,now 0.2.1.0-0~202210250659~ubuntu18.04.1 amd64 [已安装，自动]
nnstreamer-example/bionic,now 0.1.2-0~202210070126~ubuntu18.04.1 amd64 [已安装]
nnstreamer-python3/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装]
nnstreamer-single/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装，自动]
nnstreamer-tensorflow/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装]
nnstreamer-tensorflow-lite/bionic,now 2.3.0.0-0~202210310247~ubuntu18.04.1 amd64 [已安装]
```
* execute scripts got same error.
```
python3 nnstreamer_example_object_detection_tflite.py
python3 nnstreamer_example_object_detection_tflite.py  
```
* detial error information
```
Run: NNStreamer example for object detection.

** (python3:4411): WARNING **: 18:24:33.896: Cannot identify the given neural network framework, tensorflow-lite


(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps2)' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_pad_template_new: assertion 'caps != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_element_request_compatible_pad: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_object_unref: assertion 'object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps2)' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_pad_template_new: assertion 'caps != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_element_request_compatible_pad: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_object_unref: assertion 'object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(python3:4411): GStreamer-CRITICAL **: 18:24:33.914: gst_mini_object_ref: assertion 'mini_object != NULL' failed

** (python3:4411): CRITICAL **: 18:24:33.914: _check_tensors: assertion 'config->info.num_tensors >= limit' failed

** (python3:4411): CRITICAL **: 18:24:33.914: _check_tensors: assertion 'config->info.num_tensors >= limit' failed
Traceback (most recent call last):
  File "nnstreamer_example_object_detection_tflite.py", line 149, in <module>
    example.run_example()
  File "nnstreamer_example_object_detection_tflite.py", line 73, in run_example
    + self.tflite_label + ' option3=' + self.tflite_box_prior + ' option4=640:480 option5=300:300 !'
GLib.Error: gst_parse_error: could not link tensortransform0 to tensorfilter0 (3)

```
Expected Result
============

Further Information
===============
* "Ubuntu 18.04.6 LTS"
* python3.6
* x86-64

**Comment by TUT-jiayou** [comment]
* I install nnstreamer-tensorflow2-lite to fix the issue
```
sudo apt install nnstreamer-tensorflow2-lite
```
