### ISSUE TITLE
Caught SIGSEGV when delegating to EdgeTPU

### ISSUE THREAD

**Issue by zezao** [nnstreamer/nnstreamer#4194]
I'm getting SIGSEGV when trying to run the following pipeline using Coral EdgeTPU board:
```bash
root@fb915e2f726b:/usr/lib/nnstreamer/bin# gst-launch-1.0 \
>   rtspsrc location=rtsp://192.168.3.21:8556/stream1 ! rtph264depay ! avdec_h264 ! videoconvert ! videoscale ! \
>     video/x-raw,width=1024,height=576,format=RGB,pixel-aspect-ratio=1/1 ! tee name=t \
>   t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! \
>     video/x-raw,width=96,height=96,format=RGB ! tensor_converter ! \
>     other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:96:96:1 ! \
>     tensor_transform mode=arithmetic option=typecast:float32,add:0.0,mul:0.003921568859368563 \
>     queue ! tensor_filter framework=edgetpu model=yolov5s-int8-96_edgetpu.tflite custom=device_type:pci ! \
>     other/tensors,num_tensors=1,types=uint8,dimensions=85:567:1:1,format=static ! \
>     tensor_transform mode=arithmetic option=typecast:float32,add:-3.0,mul:0.009883733466267586 ! \
>     queue ! tensor_decoder mode=bounding_boxes option1=yolov5 option2=coco.txt option3=0 option4=1024:576 option5=96:96 ! \
>     video/x-raw,width=1024,height=576,format=RGBA ! mix.sink_0 \
>   t. ! queue leaky=2 max-size-buffers=10 ! mix.sink_1 \
>   compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink sync=false
Caught SIGSEGV
exec gdb failed: No such file or directory
Spinning.  Please run 'gdb gst-launch-1.0 1364' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
^\Quit
```

The model works fine when running inferences using PyCoral API and is described as:
```python
>>> interpreter = make_interpreter('yolov5s-int8-96_edgetpu.tflite')
>>> interpreter.get_input_details()
[{'name': 'input_1', 'index': 0, 'shape': array([ 1, 96, 96,  3], dtype=int32), 'shape_signature': array([ 1, 96, 96,  3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.003921568859368563, 0), 'quantization_parameters': {'scales': array([0.00392157], dtype=float32), 'zero_points': array([0], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
>>> interpreter.get_output_details()
[{'name': 'Identity', 'index': 1, 'shape': array([  1, 567,  85], dtype=int32), 'shape_signature': array([  1, 567,  85], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.009883733466267586, 3), 'quantization_parameters': {'scales': array([0.00988373], dtype=float32), 'zero_points': array([3], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```

I'm on Ubuntu 20.04.6 with the following packages (from nnstreamer's PPA):
```bash
root@fb915e2f726b:/usr/lib/nnstreamer/bin# dpkg -l |grep -E 'nns|tensor'
ii  nnstreamer:amd64                       2.3.0.0                                  amd64        NNStreamer plugins for Gstreamer
ii  nnstreamer-caffe2:amd64                2.3.0.0                                  amd64        NNStreamer Caffe2 Support
ii  nnstreamer-configuration:amd64         2.3.0.0                                  amd64        NNStreamer plugins for Gstreamer
ii  nnstreamer-core:amd64                  2.3.0.0                                  amd64        NNStreamer plugins for Gstreamer
ii  nnstreamer-datarepo:amd64              2.3.0.0                                  amd64        NNStreamer MLOps Data Repository plugin packages
ii  nnstreamer-dev:amd64                   2.3.0.0                                  amd64        NNStreamer development package
ii  nnstreamer-dev-internal:amd64          2.3.0.0                                  amd64        Development package to access internal functions of NNStreamer.
ii  nnstreamer-edge:amd64                  0.2.3.0-0~202308080100~ubuntu20.04.1     amd64        nnstreamer-edge library
ii  nnstreamer-edgetpu:amd64               2.3.0.0                                  amd64        NNStreamer Edge TPU support
ii  nnstreamer-example:amd64               0.1.2-0~202308160305~ubuntu20.04.1       amd64        Examples of nnstreamer
ii  nnstreamer-flatbuf:amd64               2.3.0.0                                  amd64        NNStreamer Flatbuf converter/decoder support
ii  nnstreamer-misc:amd64                  2.3.0.0                                  amd64        NNStreamer extra package
ii  nnstreamer-nnfw:amd64                  2.3.0.0                                  amd64        NNStreamer NNFW (ONE) support
ii  nnstreamer-openvino:amd64              2.3.0.0                                  amd64        NNStreamer OpenVino support
ii  nnstreamer-protobuf:amd64              2.3.0.0                                  amd64        NNStreamer Protobuf converter/decoder support
ii  nnstreamer-python3:amd64               2.3.0.0                                  amd64        NNStreamer Python Custom Filter Support (3.x)
ii  nnstreamer-pytorch:amd64               2.3.0.0                                  amd64        NNStreamer Pytorch Support
ii  nnstreamer-single:amd64                2.3.0.0                                  amd64        NNStreamer Single-shot
ii  nnstreamer-single-dev:amd64            2.3.0.0                                  amd64        NNStreamer single-shot development package
ii  nnstreamer-single-dev-internal:amd64   2.3.0.0                                  amd64        Development package to access internal functions of NNStreamer single-shot.
ii  nnstreamer-tensorflow:amd64            2.3.0.0-0~202304200242~ubuntu20.04.1     amd64        NNStreamer TensorFlow 1.x Support
ii  nnstreamer-tensorflow-lite:amd64       2.3.0.0-0~202304200242~ubuntu20.04.1     amd64        NNStreamer TensorFlow Lite 1.x Support
ii  nnstreamer-tensorflow2-lite:amd64      2.3.0.0                                  amd64        NNStreamer TensorFlow Lite 2.x Support
ii  nnstreamer-test-dev:amd64              2.3.0.0                                  amd64        Development package to provide testable environment of a subplugin (tensor_filter/custom).
ii  nnstreamer-tvm:amd64                   2.3.0.0                                  amd64        NNStreamer TVM support
ii  nnstreamer-util:amd64                  2.3.0.0                                  amd64        NNStreamer utility
ii  tensorflow-c                           1.13.1+nns4-0~202103030408~ubuntu20.04.1 amd64        TensorFlow provides a C API that can be used
ii  tensorflow2-lite-dev                   2.11.0-0~202212130729~ubuntu20.04.1      amd64        Tensorflow Lite development headers and object files
```
Are any packages missing?
I read some issues related to the need to install `tensorflow > 1.13.1`, do I still have this problem when using `tensorflow2-lite 2.11.0`?

I'm unsure if this is related to the model because I also tried to run a simpler pipeline (like the one suggested in https://github.com/nnstreamer/nnstreamer/issues/1966) which lead to the same error:
```bash
root@fb915e2f726b:/home/root/models# gst-launch-1.0 \
> filesrc location=/usr/lib/nnstreamer/bin/orange.png ! pngdec ! videoscale ! imagefreeze ! videoconvert ! \
> video/x-raw,format=RGB,framerate=0/1 ! tensor_converter ! \
> tensor_filter framework=edgetpu model=mobilenet_v2_1.0_224_quant_edgetpu.tflite custom=device_type:pci ! \
> filesink location=tensorfilter_edgetpu.out.log
Caught SIGSEGV
exec gdb failed: No such file or directory
Spinning.  Please run 'gdb gst-launch-1.0 2367' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
^\Quit
```

**Comment by myungjoo** [comment]
It would be very helpful if you show the stack and the code location where SIGSEGV is triggered by running gdb.

**Comment by zezao** [comment]
@myungjoo here's the gdb stack:

```bash
(gdb) run
Starting program: /usr/bin/gst-launch-1.0 rtspsrc location=rtsp://192.168.3.21:8556/stream1 \! rtph264depay \! avdec_h264 \! videoconvert \! videoscale \! video/x-raw,width=1024,height=576,format=RGB,pixel-aspect-ratio=1/1 \! tee name=t t. \! queue leaky=2 max-size-buffers=2 \! videoscale \! video/x-raw,width=96,height=96,format=RGB \! tensor_converter \! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:96:96:1 \! tensor_transform mode=arithmetic option=typecast:float32,add:0.0,mul:0.003921568859368563 queue \! tensor_filter framework=edgetpu model=yolov5s-int8-96_edgetpu.tflite custom=device_type:pci \! other/tensors,num_tensors=1,types=uint8,dimensions=85:567:1:1,format=static \! tensor_transform mode=arithmetic option=typecast:float32,add:-3.0,mul:0.009883733466267586 \! queue \! tensor_decoder mode=bounding_boxes option1=yolov5 option2=coco.txt option3=0 option4=1024:576 option5=96:96 \! video/x-raw,width=1024,height=576,format=RGBA \! mix.sink_0 t. \! queue leaky=2 max-size-buffers=10 \! mix.sink_1 compositor name=mix sink_0::zorder=2 sink_1::zorder=1 \! videoconvert \! ximagesink sync=false
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fb3046b5700 (LWP 1544)]
[Thread 0x7fb3046b5700 (LWP 1544) exited]
[New Thread 0x7fb3046b5700 (LWP 1545)]
[Thread 0x7fb3046b5700 (LWP 1545) exited]
[New Thread 0x7fb3046b5700 (LWP 1546)]
[New Thread 0x7fb303eb4700 (LWP 1547)]
[New Thread 0x7fb3036b3700 (LWP 1548)]
[New Thread 0x7fb302eb2700 (LWP 1549)]
[New Thread 0x7fb3026b1700 (LWP 1550)]
[New Thread 0x7fb301eb0700 (LWP 1551)]
[New Thread 0x7fb3016af700 (LWP 1552)]
[New Thread 0x7fb300eae700 (LWP 1553)]
[New Thread 0x7fb3006ad700 (LWP 1554)]
[New Thread 0x7fb2ffeac700 (LWP 1555)]
[New Thread 0x7fb2ff6ab700 (LWP 1556)]

Thread 1 "gst-launch-1.0" received signal SIGSEGV, Segmentation fault.
0x00007fb3053b7631 in tflite::Subgraph::OpInit(TfLiteRegistration const&, char const*, unsigned long) () from /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
(gdb) where
#0  0x00007fb3053b7631 in tflite::Subgraph::OpInit(TfLiteRegistration const&, char const*, unsigned long) () at /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
#1  0x00007fb3053ba7c4 in tflite::Subgraph::AddNodeWithParameters(std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, char const*, unsigned long, void*, TfLiteRegistration const*, int*) () at /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
#2  0x00007fb30513acb8 in tflite::InterpreterBuilder::ParseNodes(flatbuffers::Vector<flatbuffers::Offset<tflite::Operator> > const*, tflite::Subgraph*) () at /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
#3  0x00007fb30513d2ea in tflite::InterpreterBuilder::operator()(std::unique_ptr<tflite::Interpreter, std::default_delete<tflite::Interpreter> >*) () at /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
#4  0x00007fb30512cfea in nnstreamer::tensorfilter_edgetpu::edgetpu_subplugin::BuildEdgeTpuInterpreter(tflite::FlatBufferModel const&, nnstreamer::tensorfilter_edgetpu::edgetpu_subplugin_device_type, edgetpu::EdgeTpuContext*) ()
    at /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
#5  0x00007fb30512f1b8 in nnstreamer::tensorfilter_edgetpu::edgetpu_subplugin::configure_instance(_GstTensorFilterProperties const*) () at /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so
#6  0x00007fb3064fc846 in nnstreamer::tensor_filter_subplugin::cpp_open(_GstTensorFilterProperties const*, void**) () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libnnstreamer.so
#7  0x00007fb3064bf87a in gst_tensor_filter_common_open_fw () at /lib/x86_64-linux-gnu/libnnstreamer-single.so
#8  0x00007fb3064bfb9e in gst_tensor_filter_load_tensor_info () at /lib/x86_64-linux-gnu/libnnstreamer-single.so
#9  0x00007fb3064f9d9b in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libnnstreamer.so
#10 0x00007fb31178b8e0 in  () at /lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#11 0x00007fb311790b85 in  () at /lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#12 0x00007fb3064fa527 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libnnstreamer.so
#13 0x00007fb312063c08 in gst_pad_query () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#14 0x00007fb31209f6ec in gst_pad_query_caps () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#15 0x00007fb3120a02b6 in gst_element_get_compatible_pad () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#16 0x00007fb3120a1015 in gst_element_link_pads_full () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007fb3120a1936 in gst_element_link_pads_filtered () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#18 0x00007fb3120bc745 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007fb3120b2b94 in gst_parse_launch_full () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x00007fb3120b2e1f in gst_parse_launchv_full () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#21 0x0000558b1ad703b2 in  ()
#22 0x00007fb311c66083 in __libc_start_main () at /lib/x86_64-linux-gnu/libc.so.6
#23 0x0000558b1ad70c0e in  ()
(gdb)
```

**Comment by zezao** [comment]
I solved the issue by building tensorflow2-lite, and then building nnstreamer (and the plugins). libedgetpu doesn't seem to work well with newer versions of TFLite.
I built on Ubuntu 20.04 using cmake 3.16.8, TF 2.7.0, and Edge TPU w/ Runtime 14 & Compiler 16.0.

**Comment by myungjoo** [comment]
Thanks. I will let edgetpu subplugin emit compiler errors with newer versions of tflite until someone update the code for newer versions.
