### ISSUE TITLE
Dockerfile no longer builds a docker image

### ISSUE THREAD

**Issue by shortcipher3** [nnstreamer/nnstreamer#4432]
# Issue Description
The [Dockerfile found here](https://github.com/nnstreamer/nnstreamer/tree/main/tools/docker) fails to build, even when following the instructions in the `README.md`

Expected Result
============
Docker image should be built.

How to Reproduce
===============
1. `docker build .`

Further Information
===============
Here is some of my output from running:
```
Step 16/39 : RUN mk-build-deps debian/control
 ---> Running in 4fb0374fc43b
Use of uninitialized value $fullname in concatenation (.) or string at /usr/bin/equivs-build line 223.
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package 'nnstreamer-build-deps' in '../nnstreamer-build-deps_2.4.1.0_amd64.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Removing intermediate container 4fb0374fc43b
 ---> 479338009cc9
Step 17/39 : USER root
 ---> Running in 12c041448be8
Removing intermediate container 12c041448be8
 ---> e00d28c668b7
Step 18/39 : RUN apt-get -f install ./nnstreamer-build-deps*.deb &&     rm -f ./nnstreamer-build-deps*.deb &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 747ee897bd4f
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nnstreamer-build-deps : Depends: libflatbuffers-dev but it is not going to be installed
                         Depends: tensorflow2-lite-dev but it is not going to be installed
                         Depends: onnxruntime-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/bash -c apt-get -f install ./nnstreamer-build-deps*.deb &&     rm -f ./nnstreamer-build-deps*.deb &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by myungjoo** [comment]
Does it work with ```--build-arg="UBUNTU_VER=22.04"``` and adding ```gpg-agent``` in LINE 22?
(My dev machine is out of "docker" for the moment... I'm doing dist-upgrade to access newer docker. My older docker gives me "missing signature key" for any docker build.)

**Comment by shortcipher3** [comment]
I made that change and the build now shows this error:

```
+ add-apt-repository ppa:nnstreamer/ppa -u
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
Repository: 'deb https://ppa.launchpadcontent.net/nnstreamer/ppa/ubuntu/ jammy main'
Description:
package archive for nnstreamer
More info: https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/nnstreamer-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/nnstreamer-ubuntu-ppa-jammy.list
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 357, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 592, in __call__
    response, content = self.root._browser._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
Response headers:
---
connection: close
content-length: 9
content-type: text/plain;charset=utf-8
date: Thu, 18 Apr 2024 17:44:45 GMT
server: gunicorn
status: 500
x-lazr-oopsid: OOPS-4c69269818132411c1b35409d111ae14
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: eabed6d8-b8aa-449d-9e4f-d23b690cf644
x-vcs-revision: 67d34a19aaa1df7be4dd8bf498cbc5bbd785067b
---
Response body:
---
b'HTTPError'
---
```

I then navigated to the url in a browser:
https://ppa.launchpad.net/nnstreamer/ppa/ubuntu/

I got that the ssl cert was expired and the site is insecure.  I assume that is why it still fails.

**Comment by myungjoo** [comment]
At my machine, replacing 18.04 --> 22.04 and adding gpg-agent make it passes through add-apt-repository. (running the stage of ```apt-get install git build-essential pkg-config cmake ninja-build flex bison meson equivs devscripts```).

I'll add PR when the test is done

I guess the ssl cert is not the issue here although ppa.launchpad.net has invalid ssl cert, which is not a problem limited to ppa/nnstreamer.
